apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
#networking:
#  podSubnet: ${k8s_pod_cidr}

apiServer:
  extraArgs:
    cloud-provider: aws
    
controllerManager:
  extraArgs:
    cloud-provider: aws

nodeRegistration:
  kubeletExtraArgs:
    cloud-provider: aws
